//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plane
    {
        public int PlaneID { get; set; }
        public string PlaneName { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Destination { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Airport Airport { get; set; }
    }
}
